services:
    database:
        image: postgres:14-alpine
        env_file: .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend

    nginx:
        image: nginx:latest
        volumes:
            - ./conf.d:/etc/nginx/conf.d
        depends_on:
            - client
            - dashboard
        networks:
            - frontend
        ports:
            - 80:80

    client:
        build:
            context: client
            dockerfile: Dockerfile
        depends_on:
            - server
        env_file: .env
        networks:
            - frontend
        deploy:
            replicas: 3

    dashboard:
        build:
            context: dashboard
            dockerfile: Dockerfile
        depends_on:
            - server
        env_file: .env
        networks:
            - frontend

    server:
        build:
            context: participants
            dockerfile: Dockerfile
        depends_on:
            - database
        env_file: .env
        networks:
            - backend
            - frontend
        command:
            [
                "sh",
                "-c",
                "until bunx prisma migrate deploy; do echo 'A aguardar conexao com a base de dados...'; sleep 2; done && bun run ./dist/index.js",
            ]

volumes:
    postgres_data:
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
