version: "3.7"
services:
    database:
        image: prismagraphql/mongo-single-replica:4.4.3-bionic
        env_file: .env
        network_mode: host

    client:
        build:
            context: client
            dockerfile: Dockerfile
        depends_on:
            - server
        env_file: .env
        network_mode: host

    server:
        build:
            context: participants
            dockerfile: Dockerfile
        depends_on:
            - database
        env_file: .env
        network_mode: host
