version: "3.7"
services:
    mongodb_container:
        image: prismagraphql/mongo-single-replica:4.4.3-bionic
        env_file: .env
        ports:
            - 27017:27017

    nginx:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./conf.d:/etc/nginx/conf.d
        depends_on:
            - mongodb_container

    client:
        build:
            context: client
            dockerfile: Dockerfile
        ports:
            - 3000:3000
