services:
    database:
        image: postgres:14-alpine
        env_file: .env
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend

    server:
        build:
            context: participants
            dockerfile: Dockerfile
        depends_on:
            - database
        env_file: .env
        networks:
            - backend
            - frontend
        command:
            [
                "sh",
                "-c",
                "sleep 10 && bunx prisma migrate dev --skip-generate && bun run ./dist/index.js ",
            ]
        ports:
            - 3002:3002
volumes:
    postgres_data:
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
