upstream node_servers {
    least_conn;
    server localhost:3000;
}

server {
    listen 80;
    server_name corridamilleniumbim.co.mz www.corridamilleniumbim.co.mz;

    location / {
        proxy_pass http://node_servers;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
