export interface CountryCode {
    code: string;
    country: string;
}

export const provinces: { label: string; value: string }[] = [
    { label: "Maputo", value: "Maputo" },
    { label: "Gaza", value: "Gaza" },
    { label: "Inhambane", value: "Inhambane" },
    { label: "Manica", value: "Manica" },
    { label: "Sofala", value: "Sofala" },
    { label: "Tete", value: "Tete" },
    { label: "Zambézia", value: "Zambézia" },
    { label: "Nampula", value: "Nampula" },
    { label: "Cabo Delgado", value: "Cabo Delgado" },
    { label: "Niassa", value: "Niassa" },
];

export const countryCodes: CountryCode[] = [
    { code: "+93", country: "Afeganistão" },
    { code: "+355", country: "Albânia" },
    { code: "+213", country: "Argélia" },
    { code: "+376", country: "Andorra" },
    { code: "+244", country: "Angola" },
    { code: "+54", country: "Argentina" },
    { code: "+374", country: "Armênia" },
    { code: "+61", country: "Austrália" },
    { code: "+43", country: "Áustria" },
    { code: "+994", country: "Azerbaijão" },
    { code: "+973", country: "Bahrein" },
    { code: "+880", country: "Bangladesh" },
    { code: "+375", country: "Bielorrússia" },
    { code: "+32", country: "Bélgica" },
    { code: "+501", country: "Belize" },
    { code: "+229", country: "Benim" },
    { code: "+975", country: "Butão" },
    { code: "+591", country: "Bolívia" },
    { code: "+387", country: "Bósnia e Herzegovina" },
    { code: "+267", country: "Botsuana" },
    { code: "+55", country: "Brasil" },
    { code: "+673", country: "Brunei" },
    { code: "+359", country: "Bulgária" },
    { code: "+226", country: "Burquina Faso" },
    { code: "+257", country: "Burundi" },
    { code: "+855", country: "Camboja" },
    { code: "+237", country: "Camarões" },
    { code: "+1", country: "Canadá" },
    { code: "+238", country: "Cabo Verde" },
    { code: "+236", country: "República Centro-Africana" },
    { code: "+235", country: "Chade" },
    { code: "+56", country: "Chile" },
    { code: "+86", country: "China" },
    { code: "+57", country: "Colômbia" },
    { code: "+269", country: "Comores" },
    { code: "+243", country: "República Democrática do Congo" },
    { code: "+242", country: "República do Congo" },
    { code: "+682", country: "Ilhas Cook" },
    { code: "+506", country: "Costa Rica" },
    { code: "+225", country: "Costa do Marfim" },
    { code: "+385", country: "Croácia" },
    { code: "+53", country: "Cuba" },
    { code: "+357", country: "Chipre" },
    { code: "+420", country: "República Tcheca" },
    { code: "+45", country: "Dinamarca" },
    { code: "+253", country: "Djibuti" },
    { code: "+1 767", country: "Dominica" },
    { code: "+1 809", country: "República Dominicana" },
    { code: "+593", country: "Equador" },
    { code: "+20", country: "Egito" },
    { code: "+503", country: "El Salvador" },
    { code: "+240", country: "Guiné Equatorial" },
    { code: "+291", country: "Eritreia" },
    { code: "+372", country: "Estônia" },
    { code: "+251", country: "Etiópia" },
    { code: "+679", country: "Fiji" },
    { code: "+358", country: "Finlândia" },
    { code: "+33", country: "França" },
    { code: "+241", country: "Gabão" },
    { code: "+220", country: "Gâmbia" },
    { code: "+995", country: "Geórgia" },
    { code: "+49", country: "Alemanha" },
    { code: "+233", country: "Gana" },
    { code: "+30", country: "Grécia" },
    { code: "+299", country: "Groenlândia" },
    { code: "+1 473", country: "Granada" },
    { code: "+502", country: "Guatemala" },
    { code: "+224", country: "Guiné" },
    { code: "+245", country: "Guiné-Bissau" },
    { code: "+592", country: "Guiana" },
    { code: "+509", country: "Haiti" },
    { code: "+504", country: "Honduras" },
    { code: "+852", country: "Hong Kong" },
    { code: "+36", country: "Hungria" },
    { code: "+354", country: "Islândia" },
    { code: "+91", country: "Índia" },
    { code: "+62", country: "Indonésia" },
    { code: "+98", country: "Irã" },
    { code: "+964", country: "Iraque" },
    { code: "+353", country: "Irlanda" },
    { code: "+972", country: "Israel" },
    { code: "+39", country: "Itália" },
    { code: "+1 876", country: "Jamaica" },
    { code: "+81", country: "Japão" },
    { code: "+962", country: "Jordânia" },
    { code: "+7", country: "Cazaquistão" },
    { code: "+254", country: "Quênia" },
    { code: "+686", country: "Quiribati" },
    { code: "+965", country: "Kuwait" },
    { code: "+996", country: "Quirguistão" },
    { code: "+856", country: "Laos" },
    { code: "+371", country: "Letônia" },
    { code: "+961", country: "Líbano" },
    { code: "+266", country: "Lesoto" },
    { code: "+231", country: "Libéria" },
    { code: "+218", country: "Líbia" },
    { code: "+423", country: "Liechtenstein" },
    { code: "+370", country: "Lituânia" },
    { code: "+352", country: "Luxemburgo" },
    { code: "+853", country: "Macau" },
    { code: "+389", country: "Macedônia do Norte" },
    { code: "+261", country: "Madagáscar" },
    { code: "+265", country: "Malaui" },
    { code: "+60", country: "Malásia" },
    { code: "+960", country: "Maldivas" },
    { code: "+223", country: "Mali" },
    { code: "+356", country: "Malta" },
    { code: "+692", country: "Ilhas Marshall" },
    { code: "+222", country: "Mauritânia" },
    { code: "+230", country: "Maurício" },
    { code: "+52", country: "México" },
    { code: "+691", country: "Micronésia" },
    { code: "+373", country: "Moldávia" },
    { code: "+377", country: "Mônaco" },
    { code: "+976", country: "Mongólia" },
    { code: "+382", country: "Montenegro" },
    { code: "+212", country: "Marrocos" },
    { code: "+258", country: "Moçambique" },
    { code: "+95", country: "Mianmar" },
    { code: "+264", country: "Namíbia" },
    { code: "+674", country: "Nauru" },
    { code: "+977", country: "Nepal" },
    { code: "+31", country: "Países Baixos" },
    { code: "+64", country: "Nova Zelândia" },
    { code: "+505", country: "Nicarágua" },
    { code: "+227", country: "Níger" },
    { code: "+234", country: "Nigéria" },
    { code: "+683", country: "Niue" },
    { code: "+850", country: "Coreia do Norte" },
    { code: "+47", country: "Noruega" },
    { code: "+968", country: "Omã" },
    { code: "+92", country: "Paquistão" },
    { code: "+680", country: "Palau" },
    { code: "+970", country: "Palestina" },
    { code: "+507", country: "Panamá" },
    { code: "+675", country: "Papua-Nova Guiné" },
    { code: "+595", country: "Paraguai" },
    { code: "+51", country: "Peru" },
    { code: "+63", country: "Filipinas" },
    { code: "+48", country: "Polônia" },
    { code: "+351", country: "Portugal" },
    { code: "+974", country: "Catar" },
    { code: "+262", country: "Reunião" },
    { code: "+40", country: "Romênia" },
    { code: "+7", country: "Rússia" },
    { code: "+250", country: "Ruanda" },
    { code: "+685", country: "Samoa" },
    { code: "+378", country: "San Marino" },
    { code: "+239", country: "São Tomé e Príncipe" },
    { code: "+966", country: "Arábia Saudita" },
    { code: "+221", country: "Senegal" },
    { code: "+381", country: "Sérvia" },
    { code: "+248", country: "Seicheles" },
    { code: "+232", country: "Serra Leoa" },
    { code: "+65", country: "Cingapura" },
    { code: "+421", country: "Eslováquia" },
    { code: "+386", country: "Eslovênia" },
    { code: "+677", country: "Ilhas Salomão" },
    { code: "+252", country: "Somália" },
    { code: "+27", country: "África do Sul" },
    { code: "+82", country: "Coreia do Sul" },
    { code: "+211", country: "Sudão do Sul" },
    { code: "+34", country: "Espanha" },
    { code: "+94", country: "Sri Lanka" },
    { code: "+249", country: "Sudão" },
    { code: "+597", country: "Suriname" },
    { code: "+268", country: "Essuatíni" },
    { code: "+46", country: "Suécia" },
    { code: "+41", country: "Suíça" },
    { code: "+963", country: "Síria" },
    { code: "+886", country: "Taiwan" },
    { code: "+992", country: "Tajiquistão" },
    { code: "+255", country: "Tanzânia" },
    { code: "+66", country: "Tailândia" },
    { code: "+670", country: "Timor-Leste" },
    { code: "+228", country: "Togo" },
    { code: "+676", country: "Tonga" },
    { code: "+1 868", country: "Trindade e Tobago" },
    { code: "+216", country: "Tunísia" },
    { code: "+90", country: "Turquia" },
    { code: "+993", country: "Turcomenistão" },
    { code: "+688", country: "Tuvalu" },
    { code: "+256", country: "Uganda" },
    { code: "+380", country: "Ucrânia" },
    { code: "+971", country: "Emirados Árabes Unidos" },
    { code: "+44", country: "Reino Unido" },
    { code: "+1", country: "Estados Unidos" },
    { code: "+598", country: "Uruguai" },
    { code: "+998", country: "Uzbequistão" },
    { code: "+678", country: "Vanuatu" },
    { code: "+58", country: "Venezuela" },
    { code: "+84", country: "Vietnã" },
    { code: "+967", country: "Iêmen" },
    { code: "+260", country: "Zâmbia" },
    { code: "+263", country: "Zimbábue" },
];

export const countries = [
    { label: "Afeganistão", value: "Afeganistão" },
    { label: "Albânia", value: "Albânia" },
    { label: "Argélia", value: "Argélia" },
    { label: "Andorra", value: "Andorra" },
    { label: "Angola", value: "Angola" },
    { label: "Argentina", value: "Argentina" },
    { label: "Armênia", value: "Armênia" },
    { label: "Austrália", value: "Austrália" },
    { label: "Áustria", value: "Áustria" },
    { label: "Azerbaijão", value: "Azerbaijão" },
    { label: "Bahrein", value: "Bahrein" },
    { label: "Bangladesh", value: "Bangladesh" },
    { label: "Bielorrússia", value: "Bielorrússia" },
    { label: "Bélgica", value: "Bélgica" },
    { label: "Belize", value: "Belize" },
    { label: "Benim", value: "Benim" },
    { label: "Butão", value: "Butão" },
    { label: "Bolívia", value: "Bolívia" },
    { label: "Bósnia e Herzegovina", value: "Bósnia e Herzegovina" },
    { label: "Botsuana", value: "Botsuana" },
    { label: "Brasil", value: "Brasil" },
    { label: "Brunei", value: "Brunei" },
    { label: "Bulgária", value: "Bulgária" },
    { label: "Burquina Faso", value: "Burquina Faso" },
    { label: "Burundi", value: "Burundi" },
    { label: "Camboja", value: "Camboja" },
    { label: "Camarões", value: "Camarões" },
    { label: "Canadá", value: "Canadá" },
    { label: "Cabo Verde", value: "Cabo Verde" },
    { label: "República Centro-Africana", value: "República Centro-Africana" },
    { label: "Chade", value: "Chade" },
    { label: "Chile", value: "Chile" },
    { label: "China", value: "China" },
    { label: "Colômbia", value: "Colômbia" },
    { label: "Comores", value: "Comores" },
    {
        label: "República Democrática do Congo",
        value: "República Democrática do Congo",
    },
    { label: "República do Congo", value: "República do Congo" },
    { label: "Ilhas Cook", value: "Ilhas Cook" },
    { label: "Costa Rica", value: "Costa Rica" },
    { label: "Costa do Marfim", value: "Costa do Marfim" },
    { label: "Croácia", value: "Croácia" },
    { label: "Cuba", value: "Cuba" },
    { label: "Chipre", value: "Chipre" },
    { label: "República Tcheca", value: "República Tcheca" },
    { label: "Dinamarca", value: "Dinamarca" },
    { label: "Djibuti", value: "Djibuti" },
    { label: "Dominica", value: "Dominica" },
    { label: "República Dominicana", value: "República Dominicana" },
    { label: "Equador", value: "Equador" },
    { label: "Egito", value: "Egito" },
    { label: "El Salvador", value: "El Salvador" },
    { label: "Guiné Equatorial", value: "Guiné Equatorial" },
    { label: "Eritreia", value: "Eritreia" },
    { label: "Estônia", value: "Estônia" },
    { label: "Etiópia", value: "Etiópia" },
    { label: "Fiji", value: "Fiji" },
    { label: "Finlândia", value: "Finlândia" },
    { label: "França", value: "França" },
    { label: "Gabão", value: "Gabão" },
    { label: "Gâmbia", value: "Gâmbia" },
    { label: "Geórgia", value: "Geórgia" },
    { label: "Alemanha", value: "Alemanha" },
    { label: "Gana", value: "Gana" },
    { label: "Grécia", value: "Grécia" },
    { label: "Groenlândia", value: "Groenlândia" },
    { label: "Granada", value: "Granada" },
    { label: "Guatemala", value: "Guatemala" },
    { label: "Guiné", value: "Guiné" },
    { label: "Guiné-Bissau", value: "Guiné-Bissau" },
    { label: "Guiana", value: "Guiana" },
    { label: "Haiti", value: "Haiti" },
    { label: "Honduras", value: "Honduras" },
    { label: "Hong Kong", value: "Hong Kong" },
    { label: "Hungria", value: "Hungria" },
    { label: "Islândia", value: "Islândia" },
    { label: "Índia", value: "Índia" },
    { label: "Indonésia", value: "Indonésia" },
    { label: "Irã", value: "Irã" },
    { label: "Iraque", value: "Iraque" },
    { label: "Irlanda", value: "Irlanda" },
    { label: "Israel", value: "Israel" },
    { label: "Itália", value: "Itália" },
    { label: "Jamaica", value: "Jamaica" },
    { label: "Japão", value: "Japão" },
    { label: "Jordânia", value: "Jordânia" },
    { label: "Cazaquistão", value: "Cazaquistão" },
    { label: "Quênia", value: "Quênia" },
    { label: "Quiribati", value: "Quiribati" },
    { label: "Kuwait", value: "Kuwait" },
    { label: "Quirguistão", value: "Quirguistão" },
    { label: "Laos", value: "Laos" },
    { label: "Letônia", value: "Letônia" },
    { label: "Líbano", value: "Líbano" },
    { label: "Lesoto", value: "Lesoto" },
    { label: "Libéria", value: "Libéria" },
    { label: "Líbia", value: "Líbia" },
    { label: "Liechtenstein", value: "Liechtenstein" },
    { label: "Lituânia", value: "Lituânia" },
    { label: "Luxemburgo", value: "Luxemburgo" },
    { label: "Macau", value: "Macau" },
    { label: "Macedônia do Norte", value: "Macedônia do Norte" },
    { label: "Madagáscar", value: "Madagáscar" },
    { label: "Malaui", value: "Malaui" },
    { label: "Malásia", value: "Malásia" },
    { label: "Maldivas", value: "Maldivas" },
    { label: "Mali", value: "Mali" },
    { label: "Malta", value: "Malta" },
    { label: "Ilhas Marshall", value: "Ilhas Marshall" },
    { label: "Mauritânia", value: "Mauritânia" },
    { label: "Maurício", value: "Maurício" },
    { label: "México", value: "México" },
    { label: "Micronésia", value: "Micronésia" },
    { label: "Moldávia", value: "Moldávia" },
    { label: "Mônaco", value: "Mônaco" },
    { label: "Mongólia", value: "Mongólia" },
    { label: "Montenegro", value: "Montenegro" },
    { label: "Marrocos", value: "Marrocos" },
    { label: "Moçambique", value: "Moçambique" },
    { label: "Mianmar", value: "Mianmar" },
    { label: "Namíbia", value: "Namíbia" },
    { label: "Nauru", value: "Nauru" },
    { label: "Nepal", value: "Nepal" },
    { label: "Holanda", value: "Holanda" },
    { label: "Nova Zelândia", value: "Nova Zelândia" },
    { label: "Nicarágua", value: "Nicarágua" },
    { label: "Níger", value: "Níger" },
    { label: "Nigéria", value: "Nigéria" },
    { label: "Coreia do Norte", value: "Coreia do Norte" },
    { label: "Noruega", value: "Noruega" },
    { label: "Omã", value: "Omã" },
    { label: "Paquistão", value: "Paquistão" },
    { label: "Palau", value: "Palau" },
    { label: "Panamá", value: "Panamá" },
    { label: "Papua-Nova Guiné", value: "Papua-Nova Guiné" },
    { label: "Paraguai", value: "Paraguai" },
    { label: "Peru", value: "Peru" },
    { label: "Filipinas", value: "Filipinas" },
    { label: "Polônia", value: "Polônia" },
    { label: "Portugal", value: "Portugal" },
    { label: "Catar", value: "Catar" },
    { label: "Romênia", value: "Romênia" },
    { label: "Rússia", value: "Rússia" },
    { label: "Ruanda", value: "Ruanda" },
    { label: "São Marino", value: "São Marino" },
    { label: "Arábia Saudita", value: "Arábia Saudita" },
    { label: "Senegal", value: "Senegal" },
    { label: "Sérvia", value: "Sérvia" },
    { label: "Seicheles", value: "Seicheles" },
    { label: "Singapura", value: "Singapura" },
    { label: "Eslováquia", value: "Eslováquia" },
    { label: "Eslovênia", value: "Eslovênia" },
    { label: "Somália", value: "Somália" },
    { label: "África do Sul", value: "África do Sul" },
    { label: "Coreia do Sul", value: "Coreia do Sul" },
    { label: "Espanha", value: "Espanha" },
    { label: "Sri Lanka", value: "Sri Lanka" },
    { label: "Sudão", value: "Sudão" },
    { label: "Suriname", value: "Suriname" },
    { label: "Suécia", value: "Suécia" },
    { label: "Suíça", value: "Suíça" },
    { label: "Síria", value: "Síria" },
    { label: "Taiwan", value: "Taiwan" },
    { label: "Tajiquistão", value: "Tajiquistão" },
    { label: "Tanzânia", value: "Tanzânia" },
    { label: "Tailândia", value: "Tailândia" },
    { label: "Timor-Leste", value: "Timor-Leste" },
    { label: "Togo", value: "Togo" },
    { label: "Trinidad e Tobago", value: "Trinidad e Tobago" },
    { label: "Tunísia", value: "Tunísia" },
    { label: "Turquia", value: "Turquia" },
    { label: "Turcomenistão", value: "Turcomenistão" },
    { label: "Uganda", value: "Uganda" },
    { label: "Ucrânia", value: "Ucrânia" },
    { label: "Emirados Árabes Unidos", value: "Emirados Árabes Unidos" },
    { label: "Reino Unido", value: "Reino Unido" },
    { label: "Estados Unidos", value: "Estados Unidos" },
    { label: "Uruguai", value: "Uruguai" },
    { label: "Uzbequistão", value: "Uzbequistão" },
    { label: "Venezuela", value: "Venezuela" },
    { label: "Vietnã", value: "Vietnã" },
    { label: "Iémen", value: "Iémen" },
    { label: "Zâmbia", value: "Zâmbia" },
    { label: "Zimbabué", value: "Zimbabué" },
];

export const categories: { label: string; value: string }[] = [
    {
        label: "Juvenis (inscrição via Associação de Atletismo)",
        value: "Juvenis",
    },
    {
        label: "Populares - Masculino (18–39 anos)",
        value: "Populares - Masculino (18–39 anos)",
    },
    {
        label: "Populares - Feminino (18–34 anos)",
        value: "Populares - Feminino (18–34 anos)",
    },
    {
        label: "Veteranos - Masculino (40–50 anos)",
        value: "Veteranos - Masculino (40–50 anos)",
    },
    {
        label: "Veteranos - Feminino (35–45 anos)",
        value: "Veteranos - Feminino (35–45 anos)",
    },
    {
        label: "Veteranos - Masculino (>50 anos)",
        value: "Veteranos - Masculino (>50 anos)",
    },
    {
        label: "Veteranos - Feminino (>45 anos)",
        value: "Veteranos - Feminino (>45 anos)",
    },
    {
        label: "Estrangeiros - Masculino menor de 50 anos",
        value: "Estrangeiros - Masculino menor de 50 anos",
    },
    {
        label: "Estrangeiros - Feminino menor de 45 anos",
        value: "Estrangeiros - Feminino menor de 45 anos",
    },
    {
        label: "Estrangeiros - Masculino maior de 50 anos",
        value: "Estrangeiros - Masculino maior de 50 anos",
    },
    {
        label: "Estrangeiros - Feminino maior de 45 anos",
        value: "Estrangeiros - Feminino maior de 45 anos",
    },
    {
        label: "Federados (inscrição via Associação de Atletismo)",
        value: "Federados",
    },
    {
        label: "Triciclos (inscrição via Associação de Atletismo)",
        value: "Triciclos",
    },
    {
        label: "Cadeirantes (inscrição via Associação de Atletismo)",
        value: "Cadeirantes",
    },
];


export const routes: { label: string; value: string }[] = [
    {
        label: "Caminhada - 7km",
        value: "Caminhada - 7km",
    },
    {
        label: "Portadores De Deficiência - 9km",
        value: "Portadores De Deficiência - 9km",
    },
    {
        label: "Corrida Pedestre - 15km",
        value: "Corrida Pedestre - 15km",
    },
];
